// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | /interventions | 
    driver.get("https://tst.rxcc.excellus.com/interventions");
    // 2 | setWindowSize | 1296x706 | 
    driver.manage().window().setSize(new Dimension(1296, 706));
    // 3 | click | css=.p-dropdown-label | 
    driver.findElement(By.cssSelector(".p-dropdown-label")).click();
    // 4 | click | css=.p-element:nth-child(1) > .p-ripple | 
    driver.findElement(By.cssSelector(".p-element:nth-child(1) > .p-ripple")).click();
  }
}


<div role="checkbox" class="p-checkbox-box ng-tns-c92-15 p-highlight" aria-checked="true"><span class="p-checkbox-icon ng-tns-c92-15 pi pi-check"></span></div>